api:
  version: "v2"
  domainPath: "/stc"

typeorm:
  type: "postgres"
  host: "localhost"
  port: 5432
  username:
  password:
  database:
  synchronize: true
  logging: false
  entities:
    # Add your entities
    # This is a string array, use class name as value
    - "Series"
